---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - access.antware.xyz
  resources:
  - accessgrants
  - accessrequests
  - clusteraccessgrants
  - clusteraccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.antware.xyz
  resources:
  - accessgrants/finalizers
  - accessrequests/finalizers
  - clusteraccessgrants/finalizers
  - clusteraccessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - access.antware.xyz
  resources:
  - accessgrants/status
  - accessrequests/status
  - clusteraccessgrants/status
  - clusteraccessrequests/status
  verbs:
  - get
  - patch
  - update
