apiVersion: access.antware.xyz/v1alpha1
kind: ClusterAccessRequest
metadata:
  labels:
    app.kubernetes.io/name: jitaccess-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusteraccessrequest-sample
spec:
  # TODO(user): Add fields here
