apiVersion: access.antware.xyz/v1alpha1
kind: ClusterAccessResponse
metadata:
  labels:
    app.kubernetes.io/name: jit-access
    app.kubernetes.io/managed-by: kustomize
  name: clusteraccessresponse-sample
spec:
  requestRef: clusteraccessrequest-sample
  approver: admin
  response: Approved
