apiVersion: access.antware.xyz/v1alpha1
kind: AccessGrant
metadata:
  labels:
    app.kubernetes.io/name: jit-access-controller
    app.kubernetes.io/managed-by: kustomize
  name: accessgrant-sample
spec:
  # TODO(user): Add fields here
